### ISSUE TITLE
Typings are incorrect for IsObjectValidator

### ISSUE THREAD

**Issue by keithnlarsen** [retyped/node-validator-tsd-ambient#1]
This definition for IsObjectValidator is incorrect, there is no "custom" function, it is "withCustom", and it's type definition is completely wrong, it only takes a function, not a "Validatable"

instead of
`
  custom: (customValidator: Validatable) => IsObjectValidator,
`

it should be:
`
  withCustom: (customValidatorFn: Validator.ValidateFn) => IsObjectValidator,
`

**Comment by shyiko** [comment]
Hi. Thank you for pointing that out.  All type definitions under retyped/ were migrated from DefinitelyTyped in automated manner so incomplete/incorrect d.ts are expected (given quality of DefinitelyTyped typings). Anyway, this one is fixed. Thanks again! :beers:

**Comment by keithnlarsen** [comment]
Yay, thanks so much!
